package com.micatechnologies.minecraft.rcmc.track.math;

/**
 * Precomputed {@link TrackFrame}s sampled at uniform arc-length intervals along a track
 * section, generated by parallel transport.
 *
 * <p><b>The algorithm.</b> Start with an arbitrary valid frame at {@code s = 0}. At each
 * subsequent sample, rotate the previous frame's {@code up} by the same rotation that takes
 * the previous tangent to the current one (Rodrigues about their cross product). That
 * rotation is the smallest one that keeps the frame perpendicular to the curve, so the frame
 * picks up no spurious twist — a straight run of track produces literally zero rotation, and
 * a helix produces exactly the roll the helix implies and no more.</p>
 *
 * <p><b>Why precompute.</b> Transport is inherently sequential — frame <i>i</i> depends on
 * frame <i>i−1</i> — so it cannot be evaluated at an arbitrary point on demand without
 * walking the whole curve. Sampling once at track-build time and interpolating between
 * samples turns an O(n) per-query operation into O(1), which is what makes it usable from a
 * per-tick physics loop and a per-frame renderer.</p>
 *
 * <p><b>Known limitation.</b> Transport is not periodic: on a closed circuit the frame that
 * arrives back at {@code s = 0} generally differs from the starting frame by a residual roll
 * (the curve's total torsion, a real geometric quantity — the same effect as a Foucault
 * pendulum's precession). Left alone that shows as a visible seam where a car crosses the
 * start/finish. The fix is to distribute the residual linearly over the circuit when the
 * section is closed; that belongs in the track-network layer, which is the only layer that
 * knows a circuit is closed. Tracked in the master plan.</p>
 */
public final class ParallelTransportFrames {

    /** Below this angle between successive tangents, treat the section as straight. */
    private static final double MIN_ROTATION = 1.0e-9D;

    private final ArcLengthTable arcLength;
    private final TrackFrame[] frames;
    private final double spacing;

    /**
     * @param arcLength    arc-length table for the section being framed
     * @param sampleCount  number of frames, spread uniformly over the section's length.
     *                     More samples means finer roll fidelity through helices; the
     *                     interpolation between them is a nlerp of {@code up}, which is
     *                     accurate as long as neighbouring frames are close.
     */
    public ParallelTransportFrames(ArcLengthTable arcLength, int sampleCount) {
        if (arcLength == null) {
            throw new IllegalArgumentException("arcLength must not be null");
        }
        if (sampleCount < 2) {
            throw new IllegalArgumentException("sampleCount must be >= 2, got " + sampleCount);
        }
        this.arcLength = arcLength;
        this.frames = new TrackFrame[sampleCount];
        double total = arcLength.totalLength();
        this.spacing = total / (sampleCount - 1);

        Vec3 tangent = arcLength.tangentAtDistance(0.0D);
        // Seed `up` from world-up. Any perpendicular vector is a valid seed — transport only
        // guarantees the frame doesn't *acquire* twist, not that it starts at a particular
        // roll — and world-up is the one that makes a flat station platform come out level.
        frames[0] = new TrackFrame(arcLength.positionAtDistance(0.0D), tangent, Vec3.UP);

        for (int i = 1; i < sampleCount; i++) {
            double s = i * spacing;
            Vec3 nextTangent = arcLength.tangentAtDistance(s);
            Vec3 transportedUp = transport(frames[i - 1].up, tangent, nextTangent);
            frames[i] = new TrackFrame(arcLength.positionAtDistance(s), nextTangent, transportedUp);
            tangent = nextTangent;
        }
    }

    /**
     * Rotate {@code up} by the minimal rotation taking {@code fromTangent} to
     * {@code toTangent}.
     */
    private static Vec3 transport(Vec3 up, Vec3 fromTangent, Vec3 toTangent) {
        Vec3 axis = fromTangent.cross(toTangent);
        double sin = axis.length();
        if (sin < MIN_ROTATION) {
            // Tangents are parallel (straight track) or antiparallel. Antiparallel means the
            // curve doubles back on itself within one sample step, which centripetal
            // Catmull-Rom cannot produce; either way, carrying `up` through unchanged is the
            // right answer and avoids normalising a zero axis.
            return up;
        }
        double cos = fromTangent.dot(toTangent);
        double angle = Math.atan2(sin, cos);
        Vec3 unitAxis = axis.scale(1.0D / sin);

        // Rodrigues' rotation formula.
        double c = Math.cos(angle);
        double s = Math.sin(angle);
        return up.scale(c)
            .add(unitAxis.cross(up).scale(s))
            .add(unitAxis.scale(unitAxis.dot(up) * (1.0D - c)));
    }

    /** Total track length in blocks. */
    public double totalLength() {
        return arcLength.totalLength();
    }

    public int sampleCount() {
        return frames.length;
    }

    /**
     * Frame at distance {@code s} blocks along the track, interpolated between the two
     * nearest samples. {@code s} is clamped to the section.
     */
    public TrackFrame frameAtDistance(double s) {
        if (spacing <= 0.0D) {
            return frames[0];
        }
        double clamped = Math.max(0.0D, Math.min(totalLength(), s));
        double exact = clamped / spacing;
        int index = (int) exact;
        if (index >= frames.length - 1) {
            return frames[frames.length - 1];
        }

        double frac = exact - index;
        TrackFrame a = frames[index];
        TrackFrame b = frames[index + 1];

        // Exact position and tangent come from the curve, not from interpolating the samples:
        // lerping two positions cuts the corner, which would visibly sink a car into the
        // inside of a tight curve. Only `up` is interpolated, and normalised afterwards
        // (nlerp) — accurate because adjacent transported frames differ by a small angle.
        Vec3 position = arcLength.positionAtDistance(clamped);
        Vec3 forward = arcLength.tangentAtDistance(clamped);
        Vec3 up = a.up.lerp(b.up, frac).normalize();
        return new TrackFrame(position, forward, up);
    }
}
